pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID = '391369718038'
        AWS_REGION     = 'us-east-1'
        ECR_REPO_NAME  = 'tetris-game'
        ECR_REGISTRY   = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        IMAGE_TAG      = "${env.BUILD_NUMBER}"
    }

    tools {
        nodejs 'nodejs'
    }


    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('Tetris-V2') {
                    sh 'npm install'
                }
            }
        }

        stage('Build App') {
            steps {
                dir('Tetris-V2') {
                    withEnv(["NODE_OPTIONS=--openssl-legacy-provider"]) {
                        sh 'npm run build'
                    }
                }
            }
        }

        stage('SonarQube Scanning') {
            steps {
                script {
                    def scannerHome = tool 'sonar-scanner'
                    withSonarQubeEnv('sonar-server') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=davidd30_End-to-End-DevSecOps-Tetris-Project \
                            -Dsonar.organization=davidd30 \
                            -Dsonar.host.url=https://sonarcloud.io \
                            -Dsonar.sources=Tetris-V2/src
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Setup Buildx') {
            steps {
                script {
                    sh 'docker run --privileged --rm tonistiigi/binfmt --install all'
                    sh '''
                        docker buildx create --name mybuilder --use || true
                        docker buildx inspect --bootstrap
                    '''
                }
            }
        }

        stage('Build & Push Multi-Arch Image') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'aws-dorgham',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )
                ]) {
                    script {
                        echo "Logging into Amazon ECR..."
                        sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}"
        
                        echo "Building and Pushing for amd64 and arm64..."
                        sh """
                            docker buildx build \
                            --platform linux/amd64,linux/arm64 \
                            -t ${ECR_REGISTRY}/${ECR_REPO_NAME}:${IMAGE_TAG} \
                            -f Tetris-V2/Dockerfile \
                            --push Tetris-V2/.
                        """
                    }
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                script {
                    echo "Scanning Image..."
                    sh "/usr/local/bin/trivy image --severity HIGH,CRITICAL ${ECR_REGISTRY}/${ECR_REPO_NAME}:${IMAGE_TAG}"
                }
            }
        }

        // stage('Update Deployment YAML') {
        //     steps {
        //         script {
        //             def imageUri = "${ECR_REGISTRY}/${ECR_REPO_NAME}:${IMAGE_TAG}"
        //             echo "Updating deployment.yaml with ${imageUri}"
        //             sh "sed -i \"s|${ECR_REGISTRY}/${ECR_REPO_NAME}:.*|${imageUri}|g\" Tetris-V2/k8s/deployment.yaml"
        //         }
        //     }
        // }

        // stage('Push Manifest to GitHub') {
        //     steps {
        //         withCredentials([
        //             usernamePassword(
        //                 credentialsId: 'GitHub-Token', 
        //                 usernameVariable: 'GIT_USER', 
        //                 passwordVariable: 'GIT_TOKEN'
        //             )
        //         ]) {
        //             script {
        //                 sh """
        //                     git checkout main || git checkout -b main

        //                     git config user.email "david.nabil987@gmail.com"
        //                     git config user.name "Davidd30"

        //                     git add Tetris-V2/k8s/deployment.yaml
                            
        //                     if git diff-index --quiet HEAD -- Tetris-V2/k8s/deployment.yaml; then
        //                         echo "No changes detected in deployment.yaml. Skipping push."
        //                     else
        //                         git commit -m "chore: update image tag to ${IMAGE_TAG} [skip ci]"
        //                         git push https://${GIT_USER}:${GIT_TOKEN}@github.com/Davidd30/End-to-End-DevSecOps-Tetris-Project.git main
        //                     fi
        //                 """
        //             }
        //         }
        //     }
        // }

        stage('Push Manifest to GitHub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'GitHub-Token', 
                        usernameVariable: 'GIT_USER', 
                        passwordVariable: 'GIT_TOKEN'
                    )
                ]) {
                    script {
                        def imageUri = "${ECR_REGISTRY}/${ECR_REPO_NAME}:${IMAGE_TAG}"
                        
                        sh """
                            # 1. Switch to branch first (prevents checkout from overwriting local changes)
                            git checkout main || git checkout -b main
                            
                            # 2. Setup identity
                            git config user.email "david.nabil987@gmail.com"
                            git config user.name "Davidd30"

                            # 3. Apply the change NOW while on the main branch
                            echo "Updating manifest with image: ${imageUri}"
                            sed -i 's|<IMAGE_URI>|${imageUri}|g' Tetris-V2/k8s/deployment.yaml
                            
                            cat Tetris-V2/k8s/deployment.yaml

                            # 4. Stage and verify
                            git add Tetris-V2/k8s/deployment.yaml
                            
                            if git diff-index --quiet HEAD -- Tetris-V2/k8s/deployment.yaml; then
                                echo "No changes detected. The file might already be updated."
                            else
                                git commit -m "chore: update image to ${IMAGE_TAG} [skip ci]"
                                git push https://${GIT_USER}:${GIT_TOKEN}@github.com/Davidd30/End-to-End-DevSecOps-Tetris-Project.git main
                            fi
                        """
                    }
                }
            }
        }
    }
}
